sudo: required
services: 
  - docker

before_install:
  - docker build -t ahetrick22/react-test -f ./client/Dockerfile.dev ./client
  
script:
  - docker run -e CI=true ahetrick/react-test npm test -- --coverage

after_success:
  - docker build -t ahetrick22/multi-client ./client
  - docker build -t ahetrick22/multi-server ./server
  - docker build -t ahetrick22/multi-nginx ./nginx
  - docker build -t ahetrick22/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  
  - docker push ahetrick22/multi-client
  - docker push ahetrick22/multi-nginx
  - docker push ahetrick22/multi-server
  - docker push ahetrick22/multi-worker